### ISSUE TITLE
[WARN ] Blockdag is downloading blocks... : Client in initial download  module=miner

### ISSUE THREAD

**Issue by tilibougnia** [BlockdagNetworkLabs/blockdag-scripts#11]
Hi,

I have this message in log. what does that mean ?

More over howto know if the miner work properly ?

Thanks

**Comment by dev001101** [comment]
Hi @tilibougnia, The warning `[WARN ] Blockdag is downloading blocks... : Client in initial download module=miner` appears when the node is still syncing with the network. During this initial download phase, the node is catching up with the current blockchain state, so it won’t start mining until the synchronization is complete.

Once the sync process finishes, the miner will proceed with normal operations. This is expected behavior when setting up a new node or reconnecting to the network after some downtime.
